### ISSUE TITLE
[NEW FEATURE]Multi select duplicate

### ISSUE THREAD

**Issue by lduf** [org-SCAN/website#339]
**Description of the desired solution**
Select multiple duplicate to mark several duplicate as resolved

**Resolution path**
A form with checkboxes. -> values = duplicate ids.

**If the request is associated with a problem, please specify it.**
Ø

**Additional information**

Remember to adapt the tests

**Comment by vqlion** [comment]
Do you think I should remove the individual "mark as not duplicated" button in each line? Since it'll be possible to mark the duplicate as resolved from the checkbox I think it's redundant

**Comment by lduf** [comment]
@vqlion True, let's remove "mark as not duplicated" 😉
