### ISSUE TITLE
[DEPENDENCY]Update to Laravel 11

### ISSUE THREAD

**Issue by lduf** [org-SCAN/website#401]
**Description of the desired solution**
Update to laravel 10

**Resolution path**
Ø

**Comment by lduf** [comment]
Need gonoware package to be upgraded.

Seems to not be upgraded soon, check for other map package.

**Comment by lduf** [comment]
@AntoinePiron :)

**Comment by lduf** [comment]
To be done with Maps

**Comment by AntoinePiron** [comment]
Maybe for maps : https://github.com/LarsWiegers/laravel-maps

**Comment by lduf** [comment]
Now should update to Laravel 11
