### ISSUE TITLE
[NEW FEATURE]Add switch language 

### ISSUE THREAD

**Issue by lduf** [org-SCAN/website#443]
**Description of the desired solution**
Add a language switch form.
**Resolution path :**

To switch the language, you just have to call the following route :

get /language/{lang}

**Exploration :**

Save the language preference in the user profile ?
- Add a new row in user table
- Update the language through the set language section you have to develop
- Load the language preference in the middleware

**Comment by rebeccadjim** [comment]
- Check admin permission
- Check database update
- Update language
