### ISSUE TITLE
[NEW FEATURE]Choose which identity matching algorithm has to be run

### ISSUE THREAD

**Issue by lduf** [org-SCAN/website#479]
**Description of the desired solution**
We had a first algo that used the Levenstein distance between different fields. This method had the advantage of comparing all fields, not just the best descriptive value (BDV) and applies weighted comparison.
Then we worked on a solution that used phonetics to compare the different items, but this method only compared BDV.
For now, it's up to us to choose (in the code) which algo to run. And once we've chosen an algo, that's the one that's run, period.
**What would be nice is to be able to let the user choose the algo.**

In duplicate, we could imagine a dropdown with the algos and the user choosing which algo to run on the data in his team.

**Resolution path**
Top of my head :

- Create a List of algorithms (extend the model ListControl)
- Associate the class of your algorithm with the algorithm name (in your list)
- Update the DB which store the duplicate results to also store the used algorithm (store the uuid not the name 😉)
- Create the front with forms.form dropdown component
- When the user select the algo to run, update in the DB choosen duplicate algorithm (might be store in the team table (add a new colum : selected duplicate algorithm))
- Update the duplicate launcher to check which algo has to be run
- Create feature test 😉 

This is just a resolution idea that might need to be discussed.
Duplicate algorithm should have the same structure (same signature, same return type, ...) so it is not a problem to call one or another.

**If the request is associated with a problem, please specify it.**

**Additional information**

**Comment by vqlion** [comment]
> 🌍 #479 should implement new test to check :
> 
>     * same items have high similarity
> 
>     * two very different items have low similarity
